export const LIST_TEAM = 'LIST_TEAM';
export const TEAM_DETAILS = 'TEAM_DETAILS';
export const UPDATE_TEAM = 'UPDATE_TEAM';
export const SPORT_LIST = 'SPORT_LIST';
export const CHANGE_LOADING_STATE = 'CHANGE_LOADING_STATE';