export const LIST_TEAM = 'LIST_TEAM';
export const TEAM_DETAILS = 'TEAM_DETAILS';
export const UPDATE_TEAM = 'UPDATE_TEAM';
export const SPORT_LIST = 'SPORT_LIST';
export const COUNTRY_LIST = 'COUNTRY_LIST';
export const CHANGE_LOADING_STATE = 'CHANGE_LOADING_STATE';
export const CHANGE_NOTIFICATION_STATE = 'CHANGE_NOTIFICATION_STATE';
export const CHANGE_MODAL_STATE = 'CHANGE_MODAL_STATE';
export const CHANGE_NEW_TEAM_MODAL_STATE = 'CHANGE_NEW_TEAM_MODAL_STATE';
export const SET_TOASTER_INFO = 'SET_TOASTER_INFO';
export const CHANGE_PAGE_NUM = 'CHANGE_PAGE_NUM';

export const LIST_SEASON = 'LIST_SEASON';
export const FETCH_SEASON_DETAILS = 'FETCH_SEASON_DETAILS';
export const LIST_TOURNMENT = 'LIST_TOURNMENT';
export const CHANGE_NEW_SEASON_MODAL_STATE = 'CHANGE_NEW_SEASON_MODAL_STATE';
export const UPDATE_SEASON = 'UPDATE_SEASON';